### PR TITLE
update IP addresses and IP connections

### PR DESCRIPTION
**Pull request by romanojd**
This change proposes to resolve Issue #134 and related issues. Please review and ensure that I've referenced the correct RFCs. I can update the references, easily.

### CODE REVIEW

**Comment by romanojd** [comment]
Based on the discussion at LSC meeting, 1/29/2018, I split the `ip_addr` and `ip_connection` into separate v4 and v6 objects.

**Comment by romanojd** [comment]
I also added some examples back in that were taken from a previous version.
Would somebody *please* verify the referenced RFCs and the examples. Thank you.

**Comment by davaya** [comment]
#234 separates v4 and v6, and it uses one target inside IP connection.  Those are correct.

But an IP Address is not a string, and RFC 4632 (**"Classless Inter-domain Routing (CIDR): The Internet Address Assignment and Aggregation Plan"**) does not define an IP address, it defines IP network routing:

> In the simplest sense, the change from Class A/B/C network numbers to
> classless prefixes is to make explicit which bits in a 32-bit IPv4
> address are interpreted as the network number (or prefix) associated
> with a site and which are the used to number individual end systems
> within the site.

RFC 791 defines an IPv4 address - it is a single 32 bit number.
Internet Draft https://tools.ietf.org/html/draft-main-ipaddr-text-rep-00 defines the text representation of IPv4 addresses

- The pull request needs to leave the type of IPv4-Addr as Binary as defined in the IPv4 RFC.
- It needs to define a type IPv4-Net as an IPv4-Addr and a Prefix-length as defined in the CIDR RFC.
- And it needs to define the JSON serialization of IPv4-Addr and IPv4-Net as the text representation of those types.

**Comment by romanojd** [comment]
This pull request is not approved.

**Pull request closed without merging**
