### PR TITLE
Move ICMP support into lang-spec

### PR DESCRIPTION
**Pull request by alevere**
Believe the 5-tuple overload needs to be defined in lang spec.

### CODE REVIEW

**Comment by jmbrule** [comment]
Disagree, but will not dig my heels one way or the other.  I think we need more experience in this matter.  Granted, a firewall and perhaps a router will want to overload the five tuple with ICMP, but I do not want to tightly constrain at the Language level until we get more experience.  Perhaps other actuators (such as a DIT analytic) will overload the five tuple in another way or want to accommodate more layer 4 protocols.  As of now, I dont know, so until we get additional experience, I think we should AVOID over specifying at the lang level.

**Comment by alevere** [comment]
My read of the lang spec is that if you want something different, you need to extend the targets using your namespace. Below is the language spec, so I if the LS people want to weigh in and disagree, I am open to that too.

"The Targets defined in Section 3.3.1.2<https://github.com/oasis-tcs/openc2-oc2ls/blob/working/oc2ls.md#3312-target> MAY be extended using the namespace identifier as the Target name, called an extended Target namespace. One or more extended Targets for an Actuator MUST be defined within the extended Target namespace."

I will say, unlike 3.3.1.1. which uses MUST, this section is somewhat more ambiguous.
Ports are defined currently as per RFC ####.

-Alex
________________________________

**Comment by jmbrule** [comment]
The ip_connection accommodates a five tuple, with one of the elements the next protocol field.  A stateless packet filtering function is going to be concerned with the source, destination addresses, port numbers and we have identified use cases for the ICMP type and code, therefore it made sense to support in the SLPF. 
There are in excess of 100 different protocol numbers that any give IP packet may use.  In the context of the SLPF, we overloaded the five tuple to accommodate ICMP type and code.  I cannot foresee all of the use cases for all of the future actuators.   In the future, we may find that we really only need to worry about ICMP type and code and in a future iteration of the lang spec, we bubble it up.  We may also find out that some of the DIT or DAR analytics, some of the endpt remediation or other actuators define use cases where we need to accommodate codes and types for some of the other layer 4 protocols that is of no use for an SLPF. 
I dont know what the answer is at this point, so I would suggest we leave the semantics and use guidance in the SLPF.  If the future indicates that it is appropriate to bubble it up, hten so be it.  For now, would like to adhere to a principle where the language is the high level document and the nuances are in the profiles

**Comment by TobyConsidine** [comment]
I agree.

 

We need everything in the language we *need* to get the other specs out today, and then we can augment 1.1 of the language with the new requirements as they are revealed.

 

tc

**Comment by alevere** [comment]
Sounds good,

Alex
________________________________

**Comment by romanojd** [comment]
So is this being proposed now for v1.0 or deferred?

**Comment by dlemire60** [comment]
Sounds like deferred to me.

**Comment by TobyConsidine** [comment]
I also think deferred.

If we add polling or heartbeats to the Language as new Message Element Types...
Then a particular serialization that implements it
And if it includes an option or mandate for one such Message Element per request
(and remember, ICMP can be broadcast to an entire subnet)
Then they can OPT to use ICMP for this purpose

Alternately, the Language could choose to template the above,
And protocols for which ICMP is not a natural fit would have to specify how to meet this spec requirement

But not before 1.0

**Comment by alevere** [comment]
Although technically, I think we need to modify the lang spec to allow for what the pf does, I don't think it is that big of an issue and we should close it at this time. I think we could say generally in front of 5-tuple.

**Pull request closed without merging**
