### PR TITLE
Split ipv4/v6, add ip_net and binary serialization

### PR DESCRIPTION
**Pull request by davaya**
Addresses issue #134.

Alternative to Pull Request #237.

### CODE REVIEW

**Comment by dlemire60** [comment]
Shouldn't this be merged into the `working` branch, rather than the `master`?

**Comment by davaya** [comment]
Changes proposed by @sparrell are incorporated.

The language spec does not need a tutorial on information modeling, however it is an undeniable fact that an IPv4 address, defined in RFC791, *is* a 32 bit value, just as a SHA-256 hash, defined in FIPS 180 (https://csrc.nist.gov/csrc/media/publications/fips/180/4/final/documents/fips180-4-draft-aug2014.pdf), *is* a 256 bit value.

The definitions of these things have nothing to do with OpenC2, nothing to do with how any applications store them for processing, or how any standards communicate them interoperably.  They are what they are.

**Comment by dlemire60** [comment]
Minor comments / questions:

Lines 399 & 400 (**Array /ipv4-net** and v6 equivalent):  these are defined as JSON strings rather than arrays of JSON strings. I would have expected the latter. 

Lines 518 & 519, describing the connection targets: since this is text, not code, I think it would be more readable to spell out "src" and "dst". Also I could make an argument that "range" and "port" in these descriptions should both be plurals.

Line 529: should there be a reference for EUI-48 and -64, as has been provided with RFC links for the IP addressing definitions? 

Otherwise I think this looks good.

**Comment by davaya** [comment]
@dlemire60:

Yes, this should be based on the working branch, not master.  My mistake, but I don't think I can edit it now.

The consensus of the working group is that a CIDR range is transmitted as a single string as specified in the RFC: "1.2.3.4/16", not an array of two strings.

The normative reference for EUI was already merged into the working branch.

**Comment by romanojd** [comment]
This pull request was inadvertently merged with the "master" branch instead of "working". I reset the "master" branch back to commit 00a0485d. I will attempt to re-apply this pull request to the correct "working" branch.

**Comment by davaya** [comment]
#289 is the same Pull Request (updated to link RFC references) applied to "working".

Sorry for the chaos.

**Pull request merged**
