### PR TITLE
Issue 156

### PR DESCRIPTION
**Pull request by sparrell**
Words to prevent extending actions

### CODE REVIEW

**Comment by davaya** [comment]
It would be better to not use the word "extended" or "extension" - extensions are things not part of the OpenC2 standard (i.e., to extend means to write a custom actuator profile).

If the intent is that the TC shall not approve standard actuator profiles containing actions not listed in the LS, consider approving Pull Request #263 instead:

    "Each Command MUST contain exactly one Action defined in Section 3.3.1.1."

That clearly captures the conformance requirement without using the word "extend".

**Comment by sparrell** [comment]
Need to clean up 2.2 result/response

**Comment by romanojd** [comment]
I've proposed an alternative pull request to address the underlying issue: #285.

**Comment by romanojd** [comment]
Pull request #285 replaces this one. This pull request is closed.

**Pull request closed without merging**
